### PR TITLE
fix: Fix update role error

### LINKED ISSUE #276: Add guest role to user when sign up
### Bug report:
image

### PR DESCRIPTION
**Pull request by Liam-Zhao**
## Related Issue
Fixes #276 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: src/components/users/index.tsx [hunk 1]
```diff
@@ -192,10 +194,11 @@ export default function Users() {
           setLoadingButton(false);
         }
       }
-    } else if (role === 'guest') {
+    } else if (updateRole === ROLE_GUEST && role.includes(ROLE_ROOT)) {
```
Comment (gaius-qi) [inline src/components/users/index.tsx:197]: !role.includes(ROLE_GUEST)

**Review by gaius-qi — CHANGES_REQUESTED** [review]

**Review by gaius-qi — APPROVED** [review]
LGTM
